In [3]:
import pandas as pd

In [10]:
companies = pd.read_csv("../data/raw/linkedin-job-postings/companies/companies.csv")
benefits = pd.read_csv("../data/raw/linkedin-job-postings/jobs/benefits.csv")
salaries = pd.read_csv("../data/raw/linkedin-job-postings/jobs/salaries.csv")
postings = pd.read_csv("../data/raw/linkedin-job-postings/postings.csv")

## First 5 rows of companies table

In [7]:
companies.head()

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture

## (Rows, Columns)

In [13]:
companies.shape

(24473, 10)

## Number of unique values per column

In [14]:
companies.nunique()

company_id      24473
name            24428
description     24164
company_size        7
state             788
country            81
city             4124
zip_code         7779
address         19476
url             24473
dtype: int64

## Too many nulls in company_size 24473 - 21699 = 2774 nulls

In [15]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24473 entries, 0 to 24472
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_id    24473 non-null  int64
 1   name          24472 non-null  object
 2   description   24176 non-null  object
 3   company_size  21699 non-null  float64
 4   state         24451 non-null  object
 5   country       24473 non-null  object
 6   city          24472 non-null  object
 7   zip_code      24445 non-null  object
 8   address       24451 non-null  object
 9   url           24473 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.9+ MB

## Top ten columns with the highest percentage of missing values

In [17]:
companies.isna().mean().sort_values(ascending=False).head(10)

company_size    0.113349
description     0.012136
zip_code        0.001144
state           0.000899
address         0.000899
name            0.000041
city            0.000041
company_id      0.000000
country         0.000000
url             0.000000
dtype: float64

In [21]:
companies['country'].value_counts().sort_values(ascending=False).head(10)

country
US    21635
0       727
GB      620
CA      258
IN      157
DE      128
FR      118
CH       93
AU       73
NL       64
Name: count, dtype: int64

In [43]:
companies[('address')].value_counts().sort_values(ascending=False).head(10)

address
0                     3972
-                        6
New York                 6
.                        6
Downtown                 6
433 W Van Buren St       6
Headquarters             5
55 Water St              5
195 Broadway             5
175 Greenwich St         5
Name: count, dtype: int64

## WARNING: There is a country called "0" to identify nulls

In [23]:
companies['country'].unique()

array(['US', 'IE', 'OO', 'DE', 'GB', 'SE', 'FI', 'NL', 'CH', 'JP', 'FR',
       'IN', '0', 'CA', 'DK', 'AU', 'BE', 'CN', 'LU', 'IT', 'NO', 'BR',
       'MX', 'SA', 'TW', 'ZA', 'RO', 'SG', 'HK', 'IL', 'AT', 'ES', 'BM',
       'EE', 'NZ', 'IS', 'AE', 'MC', 'KR', 'LI', 'PT', 'HU', 'MT', 'VN',
       'MU', 'JM', 'PR', 'PK', 'AF', 'PH', 'UA', 'IR', 'LB', 'LT', 'PA',
       'CL', 'CR', 'KH', 'BG', 'CO', 'GR', 'SV', 'BD', 'AR', 'HN', 'CZ',
       'CY', 'KW', 'ID', 'MA', 'KE', 'PL', 'TR', 'NG', 'GE', 'AZ', 'JO',
       'KY', 'VE', 'SC', 'TZ'], dtype=object)

In [28]:
companies.groupby('company_id').size()

company_id
1009         1
1016         1
1025         1
1028         1
1033         1
            ..
103463217    1
103466352    1
103467540    1
103468936    1
103472979    1
Length: 24473, dtype: int64

In [11]:
benefits.head()

       job_id  inferred                     type
0  3887473071         0        Medical insurance
1  3887473071         0         Vision insurance
2  3887473071         0         Dental insurance
3  3887473071         0                   401(k)
4  3887473071         0  Student loan assistance

In [29]:
benefits.shape

(67943, 3)

In [30]:
benefits.nunique()

job_id      30023
inferred        2
type           12
dtype: int64

In [33]:
benefits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67943 entries, 0 to 67942
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   job_id    67943 non-null  int64
 1   inferred  67943 non-null  int64
 2   type      67943 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.6+ MB

In [34]:
benefits.isna().mean().sort_values(ascending=False).head(10)

job_id      0.0
inferred    0.0
type        0.0
dtype: float64

In [12]:
salaries.head()

,salary_id,job_id,max_salary,med_salary,min_salary,pay_period,currency,compensation_type
0,1,3884428798,NaN,20.0,NaN,HOURLY,USD,BASE_SALARY
1,2,3887470552,25.0,NaN,23.0,HOURLY,USD,BASE_SALARY
2,3,3884431523,120000.0,NaN,100000.0,YEARLY,USD,BASE_SALARY
3,4,3884911725,200000.0,NaN,10000.0,YEARLY,USD,BASE_SALARY
4,5,3887473220,35.0,NaN,33.0,HOURLY,USD,BASE_SALARY

In [9]:
postings.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0